<?php

/**
 * @file, module
 * Stored an api key in site page and returned a json object
 * Author: Debraj
 */

/**
 * Implements hook_menu().
 */
function page_json_menu() {
  $items = array();
  $items['page_json/%/%'] = array(
    'page callback' => 'page_json_create_json',
    'page arguments' => array(1,2),
    'access callback' => 'page_json_verify_key',
    'access arguments' => array(1,2),
    'file' => 'page_json.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * custom access function.
 * @params: $id : keyid
 */
function page_json_verify_key($key, $nid) {
  $access = FALSE;
  $node_type = db_query("SELECT type FROM {node} WHERE nid = :nid", array(':nid'=>$nid))->fetchField();
  if (variable_get('siteapikey') == $key && $node_type == 'page'){   
   $access = TRUE;
  }
  return $access;  
}

/**
 * Implements hook_form_alter().
 */
function page_json_form_alter(&$form, $form_state, $form_id){ 
 if ($form_id == 'system_site_information_settings'){
   $form['site_information']['siteapikey'] = array(
    '#title'=>'Site API Key',
    '#type'=>'textfield',
    '#attributes'=> array('placeholder' => 'No API Key yet'),
    '#default_value'=>variable_get('siteapikey'),
   );
   if (variable_get('siteapikey') != ''){
     $form['actions']['submit']['#value'] = 'Update Configuration';
   }
   $form['#submit'][] = 'page_json_save_api_key';
 } 
}

/**
 * Submit handler function.
 */
function page_json_save_api_key($form, $form_state){ 
 if (variable_get('siteapikey') != ''){
  drupal_set_message(t('Site API Key has been saved with the %value', array('%value' => variable_get('siteapikey'))));
 }
}